# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: private-registry-service
  namespace: portal
spec:
  selector:
    app: private-registry
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
